name: refresh-data

on:
  schedule:
  - cron: "0 16 1-30/3 * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 'release'
          crayon.enabled: 'FALSE' 
      
      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        shell: Rscript {0}

      - name: Install system dependencies
        #if: runner.os == 'Linux'
        #env:
        #  RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
          sudo apt update
          sudo apt install \
            libudunits2-dev \
            libgdal-dev \
            libgeos-dev \
            libproj-dev \
            libv8-dev \
            libjq-dev \
            libprotobuf-dev \
            protobuf-compiler
      - name: Install dependencies
        run: |
          install.packages("remotes")
          remotes::install_deps()
        shell: Rscript {0}

      - name: Render Image
        run: Rscript 'pasoapaso.R'
        
      - name: Commit results
        if: github.repository == 'robsalasco/quarantine_gs'
        run: |
          git init
          git config user.name "Roberto Salas"
          git config user.email "wala.rsalas@gmail.com"
          git config --global push.default simple
          git add .
          git status
          git commit -m 'update'
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:main --force
